/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank_application;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Suraj Topal
 */
public class History extends javax.swing.JFrame {

    /**
     * Creates new form History
     * @return 
     */
    public String fetchTableName()
    {
        String email=Login.email.getText();
        String accountno="";
        String url="jdbc:mysql://localhost:3306/demo";
        String select ="select accountno from demo.bankform where email='"+email+"'";
        try
      {      
          Class.forName("com.mysql.jdbc.Driver");
          Connection con=DriverManager.getConnection(url,"root","");
          Statement stmt=con.createStatement();
          ResultSet r=stmt.executeQuery(select);
          r.next();
          accountno=r.getString("accountno");
          System.out.println("Accountno : "+accountno);
      }
      catch(ClassNotFoundException | SQLException e)
      {
        System.out.println("Exception In Fetching Function : "+e);
      }
      return "user"+accountno;
    }
    
    public History() {
        initComponents();
         showHistory();
    }
     
     public ArrayList<User> userlist()
     {
       ArrayList<User> userlist=new ArrayList<>();
        String url="jdbc:mysql://localhost:3306/demo"; 
        try
        {
          Class.forName("com.mysql.jdbc.Driver");
          String tablename=fetchTableName();
          Connection con=DriverManager.getConnection(url,"root","");
          String query="select * from demo."+tablename+"";
          Statement st=con.createStatement();
          ResultSet rs=st.executeQuery(query);
          User user;
          while(rs.next())
          {
             user=new User(rs.getString("transactionid"),rs.getString("title"),rs.getString("date"),rs.getString("time"),rs.getString("username"),rs.getInt("amount"));
             userlist.add(user);
          }
        }
        catch(ClassNotFoundException | SQLException e)
        {
          System.out.println("Exception  : "+e);
        }
        
        return userlist;
     }
         
     public void showHistory()
     {
       ArrayList<User> list=userlist();
       DefaultTableModel model=(DefaultTableModel)table.getModel();
       Object[] row=new Object[6];
       for(int i=0;i<list.size();i++)
       {
            row[0]=list.get(i).gettransactioonid();
            row[1]=list.get(i).gettitle();
            row[2]=list.get(i).getdate();
            row[3]=list.get(i).gettime();
            row[4]=list.get(i).getusername();
            row[5]=list.get(i).getamount();
           model.addRow(row);
       }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        table.setBackground(new java.awt.Color(153, 255, 255));
        table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transactionid", "Title    ", "Date", "Time", "Username", "Amount"
            }
        ));
        table.setGridColor(new java.awt.Color(51, 51, 51));
        table.setSelectionBackground(new java.awt.Color(204, 255, 255));
        table.setSelectionForeground(new java.awt.Color(204, 255, 255));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
