/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank_application;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Suraj Topal
 */
public class Home extends javax.swing.JFrame {
 
    //set Icon in the label....
    private void scaleImage(String location, JLabel label){
        ImageIcon icon = new ImageIcon(location);
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        label.setIcon(scaledIcon);

    }   
    // This function is close the window....
 public void close(){
 
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 }        
  /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        scaleImage("F:\\HomeLogo.png",icon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bankdetails = new javax.swing.JButton();
        changepassword = new javax.swing.JButton();
        checkbalance = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        transfermoney = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        setpin = new javax.swing.JButton();
        history = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 0));
        setMinimumSize(new java.awt.Dimension(790, 430));
        setPreferredSize(new java.awt.Dimension(790, 430));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(91, 104, 227));
        jPanel1.setPreferredSize(new java.awt.Dimension(197, 419));

        bankdetails.setBackground(new java.awt.Color(51, 204, 255));
        bankdetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bankdetails.setText("Bank Details");
        bankdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankdetailsActionPerformed(evt);
            }
        });

        changepassword.setBackground(new java.awt.Color(51, 204, 255));
        changepassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        changepassword.setText("Change Password");
        changepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepasswordActionPerformed(evt);
            }
        });

        checkbalance.setBackground(new java.awt.Color(51, 204, 255));
        checkbalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkbalance.setText("Check Balance");
        checkbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbalanceActionPerformed(evt);
            }
        });

        profile.setBackground(new java.awt.Color(51, 204, 255));
        profile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        profile.setText("Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });

        transfermoney.setBackground(new java.awt.Color(51, 204, 255));
        transfermoney.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        transfermoney.setText("Transfer Money");
        transfermoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfermoneyActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(51, 204, 255));
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        setpin.setBackground(new java.awt.Color(51, 204, 255));
        setpin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setpin.setText("Set Pin");
        setpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setpinActionPerformed(evt);
            }
        });

        history.setBackground(new java.awt.Color(51, 204, 255));
        history.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        history.setText("History");
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transfermoney, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changepassword, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(setpin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(history, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(608, 608, 608))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bankdetails, changepassword, checkbalance, history, logout, profile, setpin, transfermoney});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(bankdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(changepassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkbalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transfermoney)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setpin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(history)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout)
                .addGap(5, 5, 5))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bankdetails, changepassword, checkbalance, history, logout, profile, setpin, transfermoney});

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank_application/Home.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(592, 430));
        jLabel2.setMinimumSize(new java.awt.Dimension(592, 430));
        jLabel2.setPreferredSize(new java.awt.Dimension(592, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
         
        new Profile().setVisible(true);
    }//GEN-LAST:event_profileActionPerformed

    private void changepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepasswordActionPerformed
          
        new ChangePassword().setVisible(true);        
        // TODO add your handling code here:
    }//GEN-LAST:event_changepasswordActionPerformed

    private void checkbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbalanceActionPerformed
         String url="jdbc:mysql://localhost:3306/demo";
         String email=Login.email.getText();
          String select="SELECT bankbalance FROM demo.bankform WHERE email = '"+email+"'";
        try
       {
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection con=DriverManager.getConnection(url,"root","");
                        Statement stmt=con.createStatement();
                        System.out.println("Select Statement : "+select);
                        ResultSet r=stmt.executeQuery(select);
                        r.next();
                         bankbalance=r.getInt("bankbalance");
                         con.close();
                                         
       }
        catch(SQLException | ClassNotFoundException e)
        {
           System.out.println(e); 
        }
          new Check_Balance().setVisible(true);
    }//GEN-LAST:event_checkbalanceActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        dispose();
        new Login().setVisible(true);
        // CLose the Current window..
    }//GEN-LAST:event_logoutActionPerformed

    private void transfermoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfermoneyActionPerformed
      new TransferMoney().setVisible(true);
    }//GEN-LAST:event_transfermoneyActionPerformed

    private void setpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setpinActionPerformed
        String setpin=JOptionPane.showInputDialog("Enput the Pin : ");
        
        if(setpin.length()==5)
        {     
            int pin=Integer.parseInt(setpin);
            String email=Login.email.getText();
            try
            {
                String url="jdbc:mysql://localhost:3306/demo";
                String update="update  demo.login set pin='"+pin+"' where email='"+email+"'";

               Class.forName("com.mysql.jdbc.Driver");
               Connection con=DriverManager.getConnection(url,"root","");
               Statement stmt=con.createStatement();
               stmt.executeUpdate(update);
               stmt.close();
               con.close();
            }
            catch(Exception e)
            {
             System.out.println(e);
            }
       }
       else
        {
          JOptionPane.showMessageDialog(Home.this,"Pin must must be 5 length..");
        }
    }//GEN-LAST:event_setpinActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
       new History().setVisible(true);
    }//GEN-LAST:event_historyActionPerformed

    private void bankdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankdetailsActionPerformed
           new BankDetails().setVisible(true);
    }//GEN-LAST:event_bankdetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    static public int bankbalance;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bankdetails;
    private javax.swing.JButton changepassword;
    private javax.swing.JButton checkbalance;
    private javax.swing.JButton history;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton profile;
    private javax.swing.JButton setpin;
    private javax.swing.JButton transfermoney;
    // End of variables declaration//GEN-END:variables
}
