/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank_application;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame 
{ 
    // This function is close the window....
        public void close()
        {
               WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
               Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        }
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        warning.setVisible(false);  // warning label is not showing .....
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logovar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginvar = new javax.swing.JPanel();
        User = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        warning = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        forgetpassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(750, 550));
        setResizable(false);

        logovar.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Swing\\build\\classes\\swing\\login2.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Suraj Singh Topal");

        javax.swing.GroupLayout logovarLayout = new javax.swing.GroupLayout(logovar);
        logovar.setLayout(logovarLayout);
        logovarLayout.setHorizontalGroup(
            logovarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logovarLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(logovarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );
        logovarLayout.setVerticalGroup(
            logovarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logovarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 168, Short.MAX_VALUE))
        );

        loginvar.setBackground(new java.awt.Color(255, 255, 255));

        User.setBackground(new java.awt.Color(51, 204, 255));
        User.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        User.setText("Email");
        User.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 51, 51)));
        User.setOpaque(true);

        pass.setBackground(new java.awt.Color(51, 204, 255));
        pass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pass.setText("Password");
        pass.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 51, 51)));
        pass.setOpaque(true);

        login.setBackground(new java.awt.Color(51, 204, 255));
        login.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        email.setBackground(new java.awt.Color(0, 0, 0));
        email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        password.setBackground(new java.awt.Color(0, 0, 0));
        password.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));

        warning.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        register.setBackground(new java.awt.Color(51, 153, 255));
        register.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        register.setText("Click here for new Account");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        forgetpassword.setBackground(new java.awt.Color(51, 204, 255));
        forgetpassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        forgetpassword.setText("Forget  Password");
        forgetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetpasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginvarLayout = new javax.swing.GroupLayout(loginvar);
        loginvar.setLayout(loginvarLayout);
        loginvarLayout.setHorizontalGroup(
            loginvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginvarLayout.createSequentialGroup()
                .addGroup(loginvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginvarLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(loginvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(email)
                            .addComponent(warning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(loginvarLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(forgetpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginvarLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(register)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        loginvarLayout.setVerticalGroup(
            loginvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginvarLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(loginvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forgetpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logovar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logovar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loginvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        String email=this.email.getText();
        String password=this.password.getText();
        if(email.equals("") || password.equals(""))  // check email and password is empty...
        {
            warning.setText("Empty Field");
            warning.setForeground(Color.red);
            warning.setVisible(true);
        }
        else 
        {
                 int row=0;   
                 String url="jdbc:mysql://localhost:3306/demo";
                 String select="SELECT * FROM demo.register WHERE email = '"+email+"'";
                try
                {   
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection con=DriverManager.getConnection(url,"root","");
                        Statement stmt=con.createStatement();
                        System.out.println("Select Statement : "+select);
                        ResultSet r1=stmt.executeQuery(select);
                        r1.last();   
                        row=r1.getRow();                         // It will return 1 if user already register otherwise we need to register first...
                        System.out.println("row : "+row);
                        if(row ==1)
                        {                        
                            ResultSet r=stmt.executeQuery(select);
                            r.next();
                            String pass=r.getString("password");  // Database password..

                                
                                if(pass.equals(password))   // Now check both the password is equal...
                                {
                                    warning.setVisible(false);
                                    JOptionPane.showMessageDialog(Login.this,"Login Successfull.."); 
                                    new Home().setVisible(true);  // after successfull login. It will open home page...
                                    close();
                                }
                                else
                                {
                                  warning.setVisible(true);
                                  warning.setText("Password is wrong..");
                                  warning.setForeground(Color.red);
                                }
                        }
                        else
                        {
                            warning.setVisible(true);
                            warning.setText("Please Register First");   // If the email is not match with database then we need to register first...
                            warning.setForeground(Color.red);
                        }

                            con.close();
                        }   
                        catch(SQLException | ClassNotFoundException | NumberFormatException e)
                        {
                          System.out.println(e.getMessage());
                        }
        }
    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true);  // It will show register page....
    }//GEN-LAST:event_registerActionPerformed

    private void forgetpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetpasswordActionPerformed
         new ForgetPassword().setVisible(true);
    }//GEN-LAST:event_forgetpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     Login obj= new Login();   
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel User;
    public static javax.swing.JTextField email;
    private javax.swing.JButton forgetpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    private javax.swing.JPanel loginvar;
    private javax.swing.JPanel logovar;
    private javax.swing.JLabel pass;
    public static javax.swing.JPasswordField password;
    private javax.swing.JButton register;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables

}
