package bank_application;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.ButtonGroup;
public class Register extends javax.swing.JFrame {
     public Register() 
    {
     initComponents();
     warning.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        firstname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        confirmpass = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        firstnametxt = new javax.swing.JTextField();
        lastnametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JPasswordField();
        emailtxt = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        phoneno = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        gender1 = new javax.swing.JLabel();
        confirmpasswordtxt = new javax.swing.JPasswordField();
        address = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        phonenotxt = new javax.swing.JTextField();
        addresstxt = new javax.swing.JTextField();
        dobtxt = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(712, 350));

        firstname.setBackground(new java.awt.Color(51, 204, 255));
        firstname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        firstname.setText("First Name");
        firstname.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        firstname.setOpaque(true);

        email.setBackground(new java.awt.Color(51, 204, 255));
        email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        email.setText("Email");
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        email.setOpaque(true);

        pass.setBackground(new java.awt.Color(51, 204, 255));
        pass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pass.setText("Password");
        pass.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        pass.setOpaque(true);

        confirmpass.setBackground(new java.awt.Color(51, 204, 255));
        confirmpass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        confirmpass.setText("Confirm Password");
        confirmpass.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        confirmpass.setOpaque(true);

        warning.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lastname.setBackground(new java.awt.Color(51, 204, 255));
        lastname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lastname.setText("Last Name");
        lastname.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        lastname.setOpaque(true);

        firstnametxt.setBackground(new java.awt.Color(0, 0, 0));
        firstnametxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        firstnametxt.setForeground(new java.awt.Color(255, 255, 255));
        firstnametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lastnametxt.setBackground(new java.awt.Color(0, 0, 0));
        lastnametxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lastnametxt.setForeground(new java.awt.Color(255, 255, 255));
        lastnametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        passwordtxt.setBackground(new java.awt.Color(0, 0, 0));
        passwordtxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passwordtxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        emailtxt.setBackground(new java.awt.Color(0, 0, 0));
        emailtxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        emailtxt.setForeground(new java.awt.Color(255, 255, 255));
        emailtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        register.setBackground(new java.awt.Color(51, 153, 255));
        register.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        phoneno.setBackground(new java.awt.Color(51, 204, 255));
        phoneno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        phoneno.setText("Phone No.");
        phoneno.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        phoneno.setOpaque(true);

        female.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");

        male.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");

        gender1.setBackground(new java.awt.Color(51, 204, 255));
        gender1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gender1.setText("Gender");
        gender1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        gender1.setOpaque(true);

        confirmpasswordtxt.setBackground(new java.awt.Color(0, 0, 0));
        confirmpasswordtxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        confirmpasswordtxt.setForeground(new java.awt.Color(255, 255, 255));
        confirmpasswordtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        address.setBackground(new java.awt.Color(51, 204, 255));
        address.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        address.setText("Address");
        address.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        address.setOpaque(true);

        dob.setBackground(new java.awt.Color(51, 204, 255));
        dob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dob.setText("D.O.B.");
        dob.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        dob.setOpaque(true);

        phonenotxt.setBackground(new java.awt.Color(0, 0, 0));
        phonenotxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        phonenotxt.setForeground(new java.awt.Color(255, 255, 255));

        addresstxt.setBackground(new java.awt.Color(0, 0, 0));
        addresstxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addresstxt.setForeground(new java.awt.Color(255, 255, 255));

        dobtxt.setBackground(new java.awt.Color(0, 0, 0));
        dobtxt.setForeground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(firstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(confirmpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gender1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(phoneno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(133, 133, 133)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phonenotxt)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(female, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lastnametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                        .addComponent(passwordtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                        .addComponent(emailtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                        .addComponent(firstnametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                        .addComponent(confirmpasswordtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                                    .addComponent(addresstxt)
                                    .addComponent(dobtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addresstxt, confirmpasswordtxt, dobtxt, emailtxt, firstnametxt, lastnametxt, passwordtxt, phonenotxt});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {address, confirmpass, dob, email, firstname, gender1, lastname, pass, phoneno});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmpass)
                    .addComponent(confirmpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(female)
                    .addComponent(gender1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {address, confirmpass, dob, email, firstname, gender1, lastname, pass, phoneno, warning});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addresstxt, confirmpasswordtxt, dobtxt, emailtxt, female, firstnametxt, lastnametxt, male, passwordtxt, phonenotxt});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    int dataBase(String firstname , String lastname, String email , String password,String gender,String phoneno,String address,String dob)
    {
     int row=0; 
     
     System.out.println("Phone NO : "+phoneno);
     String url="jdbc:mysql://localhost:3306/demo";
 //  String query="Select * from demo.register";
     String insert="insert into demo.register (firstname,lastname,email,password,gender,phoneno,address,dob) "+ "values (?,?,?,?,?,?,?,?)";
     String select="select * from demo.register where email='"+email+"'";
     String insertLogin="insert into demo.login (email,password,pin)"+ "values (? , ?, ?)"; 
     try
    {   
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection(url,"root","");
        Statement stmt=con.createStatement();
        System.out.println("Select Statement : "+select);
        ResultSet r=stmt.executeQuery(select);
        r.last();
        row=r.getRow();
        System.out.println("row : "+row);
        if(row==0) // row =0 means email is not already exist..
        {
            String pin="0";
            PreparedStatement ps=con.prepareStatement(insert);
            PreparedStatement login=con.prepareStatement(insertLogin);
            login.setString(1,email);
            login.setString(2,password);
            login.setString(3,pin);
            ps.setString(1, firstname);
            ps.setString(2,lastname);
            ps.setString(3,email);
            ps.setString(4, password);
                    if(male.isSelected())    // check which radio button is selected
                       ps.setString(5,"male");
                    else
                       ps.setString(5,"female");
            ps.setString(6,phoneno);
            ps.setString(7, address);
            ps.setString(8,dob);
            ps.executeUpdate();
            login.executeUpdate();
            ps.close();
            login.close();
        }
           // rs.close();
            con.close();
        }
        catch(SQLException | ClassNotFoundException | NumberFormatException e)
        {
          System.out.println(e.getMessage());
        }
     return row;
    }   
    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
       
        String firstnametxt,lastnametxt,passwordtxt,emailtxt,confirmpasswordtxt,addresstxt,phonenotxt,dobtxt="",gender="";
        SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());      
        firstnametxt=this.firstnametxt.getText();
        lastnametxt=this.lastnametxt.getText();
        passwordtxt=this.passwordtxt.getText();
        confirmpasswordtxt=this.confirmpasswordtxt.getText();
        emailtxt=this.emailtxt.getText();
        emailDuplicate=this.emailtxt.getText();
        addresstxt=this.addresstxt.getText();
        phonenotxt=this.phonenotxt.getText();   
        
        if(male.isSelected())   // set the gender based on selection
            gender="male";
        if(female.isSelected())
            gender="female";
        
                             // we used try and catch block because dob is emtpy then it will nullpointerException..that why we used..
                            try
                            {
                               dobtxt=sdf.format(this.dobtxt.getDate()); // Convert DOB into String ....
                               System.out.println("dobtxt : "+dobtxt);
                            }
                            catch(NullPointerException e)
                            {
                               System.out.println(e);
                            }
                            
         // Here we check the empty field or not ..                   
        if(dobtxt.length()== 0 || firstnametxt.equals("")|| lastnametxt.equals("")|| passwordtxt.equals("") || emailtxt.equals("")|| confirmpasswordtxt.equals("") || (male.isSelected()== false && female.isSelected()== false) ||addresstxt.equals("")|| phonenotxt.equals(""))
    {
            warning.setText("Empty Field");
            warning.setForeground(Color.red);
            warning.setVisible(true);
    }//GEN-LAST:event_registerActionPerformed
        else if(firstnametxt.length()>3 && lastnametxt.length()>3 && passwordtxt.length()>7 && confirmpasswordtxt.length()>7 && emailtxt.length()>=8 && addresstxt.length()>5 && phonenotxt.length()==10)
        {
             if(passwordtxt.equals(confirmpasswordtxt))  // check the password and confirm password must be same....
            {
             int row=dataBase(firstnametxt,lastnametxt,emailtxt,passwordtxt,gender,phonenotxt,addresstxt,dobtxt); 
                    if(row==1)       
                    {
                    warning.setText("Email is already Exist");
                    warning.setForeground(Color.red);
                    warning.setVisible(true);
                    }
                    else
                    {    
                        warning.setText("Register Successful");
                        warning.setForeground(Color.GREEN);
                        warning.setVisible(true);
                       
                        new BankAccountForm().setVisible(true);
                        dispose();
                    }
              }
             else
             {
                warning.setText("Password is not Match");
                warning.setForeground(Color.red);
                warning.setVisible(true);
             }  
        }
        else
        {
                warning.setText("Text Field is not Proper Length");   // Based on the length of the field is not sufficient..
                warning.setForeground(Color.red);
                warning.setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
       /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                new Register().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addresstxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel confirmpass;
    private javax.swing.JPasswordField confirmpasswordtxt;
    private javax.swing.JLabel dob;
    private com.toedter.calendar.JDateChooser dobtxt;
    private javax.swing.JLabel email;
    public static javax.swing.JTextField emailtxt;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField firstnametxt;
    private javax.swing.JLabel gender1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lastnametxt;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JLabel phoneno;
    private javax.swing.JTextField phonenotxt;
    private javax.swing.JButton register;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
    static String emailDuplicate; 

}